<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partinfo [
<!ELEMENT partinfo (parts,multiparts,defaults)>
<!ELEMENT parts (part*)>
<!ELEMENT part (description,price)>
<!ATTLIST part id CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT multiparts (multipart*)>
<!ELEMENT multipart (subpart*)>
<!ATTLIST multipart id CDATA #REQUIRED>
<!ELEMENT subpart (#PCDATA)>
<!ATTLIST subpart qty CDATA "1">
<!ELEMENT defaults (default*)>
<!ELEMENT default EMPTY>
<!ATTLIST default value CDATA #REQUIRED part CDATA #REQUIRED>
]>

<!--
	This file contains all the information needed by the digibom utility.
	That utility takes a CSV file generated by KiCad's EESchema's BOM generator and turns it into an order-sheet-formatted file for a Digikey order.

	Throughout this file, two different concepts are used to identify parts: part NUMBER and part VALUE.

	The part number uniquely identifies a single specific type of part.
	The part number is either a Digikey part number or a key into the multipart mapping.
	For example, RHM1.0KERCT-ND is a part number; it identifies a particular 5% 1k resistor from Rohm Semiconductor.
	XBEE is also a part number; it identifies an entry in the multipart map which itself maps to more part numbers.

	The part value identifies a larger class of part.
	The part value generally may map to more than one possible specific part, and may (or may not) have a default part mapping.
	For example, 1kR is a part value; it identifies any 1k resistor. RHM1.0KERCT-ND would be a suitable default part number for this value.
	XBEE is also a part value; it only makes sense to map it to the XBEE part number.

	Part values appear in the VALUE field in KiCad's EESchema, and thus are present in all symbols.
	Part numbers appear in the DIGIKEY PART field, also known as the USER FIELD 1, and are by default not present.
	If a symbol has a part number specified, that part number will be used.
	If a symbol has no part number, the default map will be consulted for the symbol's part value.

	Name lookups are errors.
	Any reference to a part number that cannot be found (either from a schematic symbol field, a default map entry, or a multipart subpart) is an error.
	Any schematic symbol without an explicit part number whose part value does not appear in the defaults map is an error.
	This prevents missing data from yielding an incomplete order discovered only at board assembly time.
	To avoid ordering anything for a part, use the multipart map to map a part number to zero subparts.

	A multipart expansion that (directly or indirectly) expands a part number to itself is an error.
-->
<partinfo>
	<!--
		This section is a mirror of the needed part of Digikey's database.
		It maps from a part number to the additional information about that part (description and unit price).
		All parts used should appear here.

		Prices should be in CAD from Digikey's Canadian site.
	-->
	<parts>
		<!-- Resistors, general purpose 5% -->
		<part id="RMCF0805JT1K00CT-ND">
			<description>RES 1K OHM 1/8W 5% 0805 SMD</description>
			<price>0.04000</price>
		</part>
		<part id="RMCF0805JT10K0CT-ND">
			<description>RES 10K OHM 1/8W 5% 0805 SMD</description>
			<price>0.04000</price>
		</part>
		<part id="RMCF0805JT100KCT-ND">
			<description>RES 100K OHM 1/8W 5% 0805 SMD</description>
			<price>0.04000</price>
		</part>

		<!-- Resistors, 1% -->
		<part id="RHM330AECT-ND">
			<description>RES 330 OHM 1/4W 1% 0805 SMD</description>
			<price>0.26800</price>
		</part>
		<part id="RNCP0805FTD1K50CT-ND">
			<description>RES 1.5K OHM 1/4W 1% 0805 SMD</description>
			<price>0.08000</price>
		</part>

		<!-- Capacitors, general purpose 25V or 50V -->
		<part id="490-1664-1-ND">
			<description>CAP CER 10000PF 50V 10% X7R 0805</description>
			<price>0.03100</price>
		</part>
		<part id="311-1361-1-ND">
			<description>CAP CERAMIC .1UF 50V Y5V 0805</description>
			<price>0.03100</price>
		</part>
		<part id="445-3463-1-ND">
			<description>CAP CER 1.0UF 50V Y5V 0805</description>
			<price>0.10900</price>
		</part>
		<part id="445-3469-1-ND">
			<description>CAP CER 10UF 25V Y5V 1206</description>
			<price>0.37000</price>
		</part>
		<part id="P5182-ND">
			<description>CAP 100UF 50V ALUM LYTIC RADIAL</description>
			<price>0.36000</price>
		</part>

		<!-- Silicon and packaged units -->
		<part id="102-1715-ND">
			<description>CONVERTER DC/DC REG 5V 1A</description>
			<price>7.58000</price>
		</part>
		<part id="122-1541-ND">
			<description>IC SPARTAN-3A FPGA 50K 144TQFP</description>
			<price>8.19000</price>
		</part>
		<part id="497-1492-5-ND">
			<description>IC REG LDO 3.3V 950MA TO220</description>
			<price>0.80000</price>
		</part>
		<part id="631-1125-1-ND">
			<description>OSC 8.0000 MHZ 3.3V HCMOS SMT</description>
			<price>2.02000</price>
		</part>
		<part id="BAT54JW-FDICT-ND">
			<description>DIODE SCHOTTKY ARRAY 30V SC70-6</description>
			<price>0.61000</price>
		</part>
		<part id="MCP1827S-1202E/AB-ND">
			<description>IC REG LDO 1.5A 1.2V TO-220-3</description>
			<price>1.36000</price>
		</part>
		<part id="PIC18F65J50-I/PT-ND">
			<description>IC PIC MCU FLASH 16KX16 64TQFP</description>
			<price>4.49000</price>
		</part>
		<part id="W25Q16BVSSIG-ND">
			<description>IC SPI FLASH 16MBIT 8SOIC</description>
			<price>2.80000</price>
		</part>
		<part id="XB24-AWI-001-ND">
			<description>MODULE 802.15.4 1MW W/WIRE ANT</description>
			<price>21.32000</price>
		</part>

		<!-- Connectors -->
		<part id="H11671CT-ND">
			<description>CONN RCPT USB MINI B R/A SMD</description>
			<price>1.07000</price>
		</part>
		<part id="S5751-10-ND">
			<description>CONN RECEPT 2MM SINGLE STR 10POS</description>
			<price>1.18000</price>
		</part>
		<part id="WM1744-ND">
			<description>CONN HEADER 4POS 1.25MM R/A TIN</description>
			<price>0.97000</price>
		</part>
		<part id="A25213-ND">
			<description>CONN HEADER 2POS RTANG .250 TIN</description>
			<price>1.58000</price>
		</part>
	</parts>

	<!--
		This section is the multi-part component map.
		It maps from a part number to a collection of zero or more subparts by which the main part is implemented.
		Parts should appear here if:
			(1) The part requires more than one physical part, such as an XBee (consists of a radio plus two headers), OR
			(2) The part is ordered from someone other than Digikey, such as a GA3460 transformer (ordered from Coilcraft), OR
			(3) The part is not ordered at all, such as an ICSP connector (snapped off from a standard-length SIP header)
	-->
	<multiparts>
		<!-- Chicker and ICSP headers are snapped off from a standard-length SIP header. -->
		<multipart id="chicker-header" />
		<multipart id="ICSP" />

		<!-- XBees require both the radio and two headers with the unusual pin spacing of 2mm. -->
		<multipart id="XBEE">
			<subpart>XB24-AWI-001-ND</subpart>
			<subpart qty="2">S5751-10-ND</subpart>
		</multipart>
	</multiparts>

	<!--
		This section is the default part selection.
		It maps from a part value to a part number.
		Values should appear here if:
			(1) A suitable default part can be chosen for a value (for example, the value "1kR" can default to a specific 5% 1k resistor), OR
			(2) The value inherently identifies a single part (for example, the value "BAT54JW" identifies a precise model of diode package)

		In all cases, if the "Digikey Part" field is filled in in the schematic symbol, that field will override this default mapping.
	-->
	<defaults>
		<default value="1kR" part="RMCF0805JT1K00CT-ND" />
		<default value="10kR" part="RMCF0805JT10K0CT-ND" />
		<default value="100kR" part="RMCF0805JT100KCT-ND" />
		<default value="10nF" part="490-1664-1-ND" />
		<default value="100nF" part="311-1361-1-ND" />
		<default value="1uF" part="445-3463-1-ND" />
		<default value="10uF" part="445-3469-1-ND" />
		<default value="100uF" part="P5182-ND" />
		<default value="BAT54JW" part="BAT54JW-FDICT-ND" />
		<default value="FXO-HC73" part="631-1125-1-ND" />
		<default value="ICSP" part="ICSP" />
		<default value="LD1117V33C" part="497-1492-5-ND" />
		<default value="MCP1827S-1202E/AB" part="MCP1827S-1202E/AB-ND" />
		<default value="PIC18F65J50" part="PIC18F65J50-I/PT-ND" />
		<default value="V7805-1000" part="102-1715-ND" />
		<default value="W25Q16BV" part="W25Q16BVSSIG-ND" />
		<default value="XBEE" part="XBEE" />
		<default value="XC3S50A-TQ144" part="122-1541-ND" />
	</defaults>
</partinfo>
