<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-info [
<!ELEMENT project-info (multiparts,defaults)>
<!ELEMENT multiparts (multipart*)>
<!ELEMENT multipart (subpart*)>
<!ATTLIST multipart id CDATA #REQUIRED>
<!ELEMENT subpart EMPTY>
<!ATTLIST subpart id CDATA #REQUIRED quantity CDATA "1">
<!ELEMENT defaults (default*)>
<!ELEMENT default EMPTY>
<!ATTLIST default value CDATA #REQUIRED part CDATA #REQUIRED>
]>

<!--
	This file contains all the information needed by the digibom utility.
	That utility takes CSV file(s) generated by KiCad's EESchema's BOM generator and turns it into an order-sheet-formatted file for a Digikey order.

	Throughout this file, two different concepts are used to identify parts: part NUMBER and part VALUE.

	The part number uniquely identifies a single specific type of part.
	The part number is either a Digikey part number or a key into the multipart mapping.
	For example, RHM1.0KERCT-ND is a part number; it identifies a particular 5% 1k resistor from Rohm Semiconductor.
	XBEE is also a part number; it identifies an entry in the multipart map which itself maps to more part numbers.

	The part value identifies a larger class of part.
	The part value generally may map to more than one possible specific part, and may (or may not) have a default part mapping.
	For example, 1kR is a part value; it identifies any 1k resistor. RHM1.0KERCT-ND would be a suitable default part number for this value.
	XBEE is also a part value; it only makes sense to map it to the XBEE part number.

	Part values appear in the VALUE field in KiCad's EESchema, and thus are present in all symbols.
	Part numbers appear in the DIGIKEY PART field, also known as the USER FIELD 1, and are by default not present.
	If a symbol has a part number specified, that part number will be used.
	If a symbol has no part number, the default map will be consulted for the symbol's part value.

	Name lookup failures are errors.
	Any reference to a part number that cannot be found (either from a schematic symbol field, a default map entry, or a multipart subpart) is an error.
	Any schematic symbol without an explicit part number whose part value does not appear in the defaults map is an error.
	This prevents missing data from yielding an incomplete order discovered only at board assembly time.
	To avoid ordering anything for a part, use the multipart map to map a part number to zero subparts.

	A multipart expansion that (directly or indirectly) expands a part number to itself is an error.
-->
<project-info>
	<!--
		This section is the multi-part component map.
		It maps from a part number to a collection of zero or more subparts by which the main part is implemented.
		Parts should appear here if:
			(1) The part requires more than one physical part, such as an XBee (consists of a radio plus two headers), OR
			(2) The part is ordered from someone other than Digikey, such as a GA3460 transformer (ordered from Coilcraft), OR
			(3) The part is not ordered at all, such as an ICSP connector (snapped off from a standard-length SIP header)
	-->
	<multiparts>
		<!-- Battery inlet consists of a pair of holes with soldered wires, not a component. -->
		<multipart id="battery-inlet" />

		<!-- Chicker, dribbler, ICSP, and other headers are snapped off from a standard-length SIP header. -->
		<multipart id="chicker-header" />
		<multipart id="dribbler-header" />
		<multipart id="ICSP" />
		<multipart id="2.54mm-header-general" />

		<!-- Chicker boost regulator inductor is ordered from CoilCraft. -->
		<multipart id="chicker-charge-inductor" />

		<!-- E4P optical encoder kit is ordered from US Digital. -->
		<multipart id="E4P" />

		<!-- Some components are just representations of jumper wires between two points. -->
		<multipart id="jumper-wire" />

		<!-- The kicker solenoid is manufactured locally, not purchased. -->
		<multipart id="KICKER_SOLENOID" />

		<!-- Long-pin headers are one assembly per chicker board; they come in 5×1 lengths and each board needs 7×2 plus 2×1. -->
		<multipart id="long-pin-male-header">
			<subpart id="609-4535-1-ND" quantity="4" />
		</multipart>
		<multipart id="long-pin-male-header2" />

		<!-- An M3 mounting system consists solely of a hole in the board; the mechanical team takes care of nuts and bolts. -->
		<multipart id="M3_MOUNT" />

		<!-- The mainboard may need one of a handful of different fuse values. -->
		<multipart id="mainboard-fuses">
			<subpart id="486-1684-1-ND" />
			<subpart id="486-1686-1-ND" />
			<subpart id="486-1687-1-ND" />
			<subpart id="486-1688-1-ND" />
			<subpart id="486-1690-1-ND" />
		</multipart>

		<!-- An MRF24J40MC requires an external antenna. -->
		<multipart id="MRF24J40MC">
			<subpart id="MRF24J40MCT-I/RMCT-ND" />
			<subpart id="0600-00039-ND" />
		</multipart>
	</multiparts>

	<!--
		This section is the default part selection.
		It maps from a part value to a part number.
		Values should appear here if:
			(1) A suitable default part can be chosen for a value (for example, the value "1kR" can default to a specific 5% 1k resistor), OR
			(2) The value inherently identifies a single part (for example, the value "BAT54JW" identifies a precise model of diode package)

		In all cases, if the "Digikey Part" field is filled in in the schematic symbol, that field will override this default mapping.
	-->
	<defaults>
		<default value="4.99R" part="541-4.99CCCT-ND" />
		<default value="16.5R" part="541-16.5CCT-ND" />
		<default value="88.7R" part="541-88.7CCT-ND" />
		<default value="100R" part="311-100CRCT-ND" />
		<default value="1kR" part="CR0805-FX-1001ELFCT-ND" />
		<default value="2.2kR" part="311-2.20KCRCT-ND" />
		<default value="10kR" part="311-10.0KCRCT-ND" />
		<default value="100kR" part="311-100KCRCT-ND" />
		<default value="15pF" part="490-5532-1-ND" />
		<default value="27pF" part="478-5017-1-ND" />
		<default value="10nF" part="490-1664-1-ND" />
		<default value="100nF" part="311-1361-1-ND" />
		<default value="470nF" part="311-1364-1-ND" />
		<default value="1uF" part="445-3463-1-ND" />
		<default value="2.2uF" part="587-1292-1-ND" />
		<default value="4.7uF" part="587-1782-1-ND" />
		<default value="10uF" part="445-3469-1-ND" />
		<default value="100uF" part="P5182-ND" />
		<default value="74AHC74" part="568-4458-1-ND" />
		<default value="7805" part="LM7805CT-ND" />
		<default value="ADS7866IDBVT" part="296-18216-1-ND" />
		<default value="AO4616" part="785-1043-1-ND" />
		<default value="E4P" part="E4P" />
		<default value="FT232" part="768-1007-1-ND" />
		<default value="ICSP" part="ICSP" />
		<default value="LD1117V33C" part="497-1492-5-ND" />
		<default value="MCP1415" part="MCP1415T-E/OTCT-ND" />
		<default value="MIC7300" part="576-1319-1-ND" />
		<default value="MRF24J40MB" part="MRF24J40MB-I/RM-ND" />
		<default value="MRF24J40MC" part="MRF24J40MC" />
		<default value="OPB733TR" part="365-1510-1-ND" />
		<default value="PIC18F65J50" part="PIC18F65J50-I/PT-ND" />
		<default value="PIC18F67J50" part="PIC18F67J50-I/PT-ND" />
		<default value="PNA2602M-ND" part="PNA2602M-ND" />
		<default value="RURG3060CC" part="RURG3060CC-ND" />
		<default value="SD1209T3-A1" part="445-2530-ND" />
		<default value="STM32F405RXT" part="497-11767-ND" />
		<default value="TC4469" part="TC4469COE-ND" />
		<default value="TEMT1000" part="751-1052-1-ND" />
		<default value="VSMY2850RG" part="VSMY2850RGCT-ND" />
		<default value="W25Q16BV" part="W25Q16BVSSIG-ND" />
		<default value="XC6222B331PR" part="893-1138-1-ND" />
	</defaults>
</project-info>
